server:
  port: 8000
  tomcat:
    max-http-form-post-size: 3MB
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: api-gateway-service
  profiles:
    include: env
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/me/**
            - Method=GET,PUT
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh